import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navigation from '../components/Nav'
import Hero from '../sections/Hero'
import ModelHomes from '../sections/ModelHomes'
import Developments from '../sections/Developments'
import About from '../sections/About'
import Footer from '../sections/Footer';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Policella Homes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <ModelHomes />
      <Developments />
      <About />
    </>
  )
}
