import Head from 'next/head'
import Hero from '../components/Hero'
import Preamble from '../components/Preamble'
import ModelHomes from '../components/ModelHomes'
import Developments from '../components/Developments'
import About from '../components/About'
import homes from '../public/data/model_homes_data.json'


export default function Home() {

  return (
    <>
      <Head>
        <title>Policella Homes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Preamble />
      <ModelHomes />
      <div className="wrapper">
        <hr />
      </div>
      <Developments />
      <About />
    </>
  )
}
